apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"echo"},"name":"echo","namespace":"oat-gitops"},"spec":{"ports":[{"name":"high","port":8080,"protocol":"TCP","targetPort":8080},{"name":"low","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"echo"}}}
  labels:
    app: echo
  name: echo
  namespace: oat-gitops
spec:
  ports:
  - name: high
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: low
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
